kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bm-local
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        apiVersion: kubelet.config.k8s.io/v1beta1
        cgroupDriver: cgroupfs
    # Mount host directories so containers can read data / write artifacts locally
    extraMounts:
      - hostPath: ./data
        containerPath: /data
      - hostPath: ./artifacts
        containerPath: /artifacts
