apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-marketing-api
  namespace: bank-marketing
  labels:
    app: bank-marketing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-marketing-api
  template:
    metadata:
      labels:
        app: bank-marketing-api
    spec:
      containers:
        - name: api
          image: bankmarketingacr.azurecr.io/bank-marketing-api:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: UVICORN_WORKERS
              value: "1"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: bank-marketing-api-key
                  key: API_KEY
      imagePullSecrets:
        - name: acr-secret
